#!/usr/bin/env bash

# apply folder based tags to incoming mail
sync_tags () {

    notmuch tag --batch <<EOF
+inbox  -- folder:$1/inbox
+sent   -- folder:$1/sent
+drafts -- folder:$1/draft
+trash  -- folder:$1/trash
EOF
    # draft is handled automatically
}

sync_tags mw
sync_tags cse

echo done
